version: '2'

services:
  app:
    build:
      context: ./docker/app
    volumes:
     - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root99
      - MYSQL_PASSWORD=@imovel2020
      - MYSQL_ROOT_PASSWORD=@imovel2020
      - MYSQL_DATABASE=imobiliaria

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8180:80
    links:
      - database:database
    environment:
      - PMA_HOST=database
      - MYSQL_USER=root99
      - MYSQL_PASSWORD=@imovel2020
      - MYSQL_ROOT_PASSWORD=@imovel2020
